import { Sprite as _Sprite } from './sprite';
import { Loader as _Loader } from './loader';
import { Animate as _Animate } from './animate';
import { LongTake as _LongTake } from './longtake';
export declare type Sprite = _Sprite;
export declare type Loader = _Loader;
export declare type Animate = _Animate;
export declare type LongTake = _LongTake;
export declare const Sprite: typeof _Sprite;
export declare const Loader: typeof _Loader;
export declare const Animate: typeof _Animate;
export declare const LongTake: typeof _LongTake;
export default LongTake;
